name: 'steam_pipeline'
version: '1.0.0'
profile: 'steam-pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  steam_pipeline:
    staging:
      +materialized: view
    mart:
      +materialized: table
