version: '3.8'

services:


#Set up the database to store the docker metadata
  postgres:
    image: postgres:13
    enviroment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow 
      - POSTGRES_DB=airflow 
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7.2-bookworm
    expose: 
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

