version: 2

models:
  - name: staging_steam_games
    description: One to one with model of raw games source cleaned 
    config:
      contract:
        enforced: true
    columns:

      - name: app_id
        description: Unique id for each steam app 
        data_type: number
        tests:
          - not_null
          - unique
      
      - name: name
        description: The name of the steam app
        data_type: varchar

      - name: is_free
        description: Wether or not the app is a free to play game 
        data_type: boolean

      - name: price
        description: The price of the app in USD
        data_type: number

      - name: release_date
        description: The release date of the app
        data_type: ??????

      - name: developer
        description: The names of the different developers for the app
        data_type: varchar

      - name: publisher
        description: The names of the different publishers for an app
        data_type: varchar

      - name: 
