version: 2

models:
  - name: staging_steam_games
    description: One-to-one cleaned staging model of the raw Steam games source
    config:
      contract:
        enforced: true
    columns:
      - name: app_id
        description: Unique id for each Steam app
        data_type: number
        tests:
          - not_null
          - unique
      
      - name: name
        description: The name of the Steam app
        data_type: varchar

      - name: is_free
        description: Whether the app is free to play
        data_type: boolean

      - name: price
        description: The price of the app in USD
        data_type: number

      - name: release_date
        description: The release date of the app
        data_type: date

      - name: developer
        description: The developer names for the app
        data_type: varchar

      - name: publisher
        description: The publisher names for the app
        data_type: varchar

      - name: genres
        description: The genres associated with the app
        data_type: varchar

      - name: categories
        description: The categories associated with the app
        data_type: varchar

      - name: platforms
        description: The platforms supported by the app
        data_type: varchar

      - name: metacritic_score
        description: The Metacritic score for the app
        data_type: number

      - name: recommendations
        description: The number of user recommendations for the app
        data_type: number

      - name: short_description
        description: A short description of the app
        data_type: varchar

      - name: languages
        description: Supported languages for the app
        data_type: varchar
