# Airbyte services - can be run separately or with main compose
services:
  # Airbyte services
  x-airbyte-common:
    &airbyte-common
    environment:
      &airbyte-common-env
      - AIRBYTE_VERSION=0.50.40
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_DB=airbyte
      - CONFIG_ROOT=/data
      - TRACKING_STRATEGY=logging
      - WORKSPACE_ROOT=/tmp/airbyte_local
      - LOCAL_ROOT=/tmp/airbyte_local
      - LOCAL_DOCKER_MOUNT=/var/lib/docker/overlay2/
    volumes:
      - airbyte-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      &airbyte-common-depends-on
      airbyte-db:
        condition: service_healthy
    restart: always

  airbyte-server:
    <<: *airbyte-common
    image: airbyte/server:latest
    container_name: airbyte-server
    environment:
      <<: *airbyte-common-env
      - WEBAPP_URL=http://localhost:8000/
      - API_URL=http://localhost:8001/
    ports:
      - "8000:8000"
      - "8001:8001"

  airbyte-worker:
    <<: *airbyte-common
    image: airbyte/worker:latest
    container_name: airbyte-worker

  airbyte-db:
    image: postgres:13
    container_name: airbyte-db
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbyte
    volumes:
      - airbyte-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airbyte"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  airbyte-data:
  airbyte-db-data:
